# This is a basic workflow to help you get started with Actions

name: release

on:
  push:
    branches: [issue-**]
  # pull_request:
  #   branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Build
        run: |
          cd slackdeck/
          npm i
          npm run dev
          npm run build
          echo 'Build complete!'
      - name: Zip
        run: |
          cd slackdeck/dist/
          zip release.zip *.*
          pwd
          echo 'Zip complete!'

      - name: Create new tag
        id: create_tag
        run: |
          cat slackdeck/dist/manifest.json | jq -r '.version'
          VERSION=$(cat slackdeck/dist/manifest.json | jq -r '.version')
          echo "::set-output name=new_tag::$VERSION"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: test_v${{ steps.create_tag.outputs.new_tag }}
          release_name: Release ${{ steps.create_tag.outputs.new_tag }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: Upload release asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/release.zip
          asset_name: chrome-extention.zip
          asset_content_type: application/zip
